// export const operators = [
//   {
//     id: 1,
//     name: 'Govind Kr Navik',
//     avatar: 'G',
//     avatarBg: '#FEF3E7',
//     avatarColor: '#F18805',
//     location: 'Mumbai, Maharashtra',
//     experience: '0-2 Years',
//     equipment: ['Tower Crane', 'Backhoe'],
//     certified: true,
//     licensed: false,
//     phoneNumber: '+91 9876543210',
//     email: 'govind.navik@example.com',
//     joinedDate: 'January 2023',
//     availability: 'Available from April 15, 2025',
//     certifications: ['Heavy Equipment Operation Level 1', 'Safety Training Certificate'],
//     previousProjects: ['Highrise Construction - Mumbai', 'Infrastructure Project - Pune']
//   },
//   {
//     id: 2,
//     name: 'Md Barkat Ali',
//     avatar: 'M',
//     avatarBg: '#FEF3E7',
//     avatarColor: '#F18805',
//     location: 'Delhi NCR',
//     experience: '0-5 Years',
//     equipment: ['Forklift'],
//     certified: false,
//     licensed: true,
//     phoneNumber: '+91 9876543210',
//     email: 'barkat.ali@example.com',
//     joinedDate: 'March 2022',
//     availability: 'Available immediately',
//     certifications: ['Forklift Operator License', 'Material Handling Certification'],
//     previousProjects: ['Warehouse Project - Delhi', 'Factory Setup - Gurgaon']
//   },
//   {
//     id: 3,
//     name: 'Varun Jha',
//     avatar: 'V',
//     avatarBg: '#FEF3E7',
//     avatarColor: '#F18805',
//     location: 'Bangalore, Karnataka',
//     experience: '0-5 Years',
//     equipment: ['Batching Plant'],
//     certified: true,
//     licensed: true,
//     phoneNumber: '+91 9876543210',
//     email: 'varun.jha@example.com',
//     joinedDate: 'July 2021',
//     availability: 'Available from March 20, 2025',
//     certifications: ['Concrete Plant Operation', 'Quality Control'],
//     previousProjects: ['Commercial Building - Bangalore', 'Residential Township - Mysore']
//   },
//   {
//     id: 4,
//     name: 'Sandip Jagtap',
//     avatar: 'S',
//     avatarBg: '#FEF3E7',
//     avatarColor: '#F18805',
//     location: 'Pune, Maharashtra',
//     experience: '0-10 Years',
//     equipment: ['Batching Plant'],
//     certified: true,
//     licensed:false,
//     phoneNumber: '+91 9876543210',
//     email: 'sandip.jagtap@example.com',
//     joinedDate: 'August 2019',
//     availability: 'Available immediately',
//     certifications: ['Advanced Plant Operations', 'Mechanical Troubleshooting'],
//     previousProjects: ['Highway Project - Maharashtra', 'Dam Construction - Karnataka']
//   },
//   {
//     id: 5,
//     name: 'Chhotu Kumar',
//     avatar: 'C',
//     avatarBg: '#FEF3E7',
//     avatarColor: '#F18805',
//     location: 'Hyderabad, Telangana',
//     experience: '10+ Years',
//     equipment: ['Excavator'],
//     certified: false,
//     licensed: true,
//     phoneNumber: '+91 9876543210',
//     email: 'chhotu.kumar@example.com',
//     joinedDate: 'December 2014',
//     availability: 'Available from April 1, 2025',
//     certifications: ['Master Excavator Operator', 'Site Safety Manager'],
//     previousProjects: ['Metro Project - Hyderabad', 'Commercial Complex - Vijayawada']
//   },
//   {
//     id: 6,
//     name: 'Bittu Bhupendra',
//     avatar: 'B',
//     avatarBg: '#FEF3E7',
//     avatarColor: '#F18805',
//     location: 'Chennai, Tamil Nadu',
//     experience: '0-10 Years',
//     equipment: ['Batching Plant'],
//     certified: true,
//     licensed: true,
//     phoneNumber: '+91 9876543210',
//     email: 'bittu.bhupendra@example.com',
//     joinedDate: 'April 2018',
//     availability: 'Available immediately',
//     certifications: ['Concrete Mix Specialist', 'Plant Maintenance'],
//     previousProjects: ['IT Park Development - Chennai', 'Beach Resort Construction - Pondicherry']
//   },
//   {
//     id: 7,
//     name: 'Amit Mishra',
//     avatar: 'A',
//     avatarBg: '#FEF3E7',
//     avatarColor: '#F18805',
//     location: 'Kolkata, West Bengal',
//     experience: '10+ Years',
//     equipment: ['Excavator engineer'],
//     certified: false,
//     licensed: true,
//     phoneNumber: '+91 9876543210',
//     email: 'amit.mishra@example.com',
//     joinedDate: 'November 2013',
//     availability: 'Available from March 25, 2025',
//     certifications: ['Professional Engineer License', 'Heavy Equipment Specialist'],
//     previousProjects: ['Bridge Construction - Kolkata', 'Underground Metro - Howrah']
//   },
//   {
//     id: 8,
//     name: 'Vishal Seth',
//     avatar: 'V',
//     avatarBg: '#FEF3E7',
//     avatarColor: '#F18805',
//     location: 'Ahmedabad, Gujarat',
//     experience: '0-10 Years',
//     equipment: ['Crane Engineer'],
//     certified: true,
//     licensed: false,
//     phoneNumber: '+91 9876543210',
//     email: 'vishal.seth@example.com',
//     joinedDate: 'June 2017',
//     availability: 'Available immediately',
//     certifications: ['Crane Safety Inspector', 'Engineering License'],
//     previousProjects: ['Industrial Complex - Ahmedabad', 'Port Development - Surat']
//   },
//   {
//     id: 9,
//     name: 'Mannu Dave',
//     avatar: 'M',
//     avatarBg: '#FEF3E7',
//     avatarColor: '#F18805',
//     location: 'Jaipur, Rajasthan',
//     experience: '0-2 Years',
//     equipment: ['Site Dumper'],
//     certified: true,
//     licensed: true,
//     phoneNumber: '+91 9876543210',
//     email: 'mannu.dave@example.com',
//     joinedDate: 'May 2023',
//     availability: 'Available from April 10, 2025',
//     certifications: ['Commercial Driving License', 'Material Transport Specialist'],
//     previousProjects: ['Heritage Restoration - Jaipur', 'Resort Development - Udaipur']
//   }
// ];